POST https://vamshincue4njscpfvwof.drops.nxtwave.tech/register/

Content-Type : application/json

{
  "username": "raju7",
  "name": "RajuBontha",
  "password": "raju@1432",
  "gender": "male",
  "location": "Detroit"
}
###

POST https://vamshincue4njscpfvwof.drops.nxtwave.tech/login/

Content-Type : application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}
###

PUT https://vamshincue4njscpfvwof.drops.nxtwave.tech/change-password/

Content-Type : application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}